### ISSUE TITLE
Something wrong with the data for syntax analysis

### ISSUE THREAD

**Issue by HuXiangkun** [clarkkev/attention-analysis#10]
Hi, I found that dev_attn.pkl and train_attn.pkl for syntax analysis have all heads of 0. And the relns are all 'root'.

**Comment by clarkkev** [comment]
As the README says, we release dummy labels for the dependency parsing analysis because the WSJ annotations are not publicly available. However, you can get the annotations through [LDC](https://catalog.ldc.upenn.edu/LDC99T42) or use different dependency parsing data as discussed [here](https://github.com/clarkkev/attention-analysis/issues/1).
